"""PostgreSQL schema helpers for Supabase/Render deployments."""
import logging
import threading

from .db import get_db_connection
from .product_measurements import migrate_legacy_measurements_to_table, sync_missing_product_measurements

_logger = logging.getLogger(__name__)

_schema_lock = threading.Lock()
_schema_initialized = False


def ensure_postgres_schema():
    """Apply DDL once per process (hot paths call this safely)."""
    global _schema_initialized
    if _schema_initialized:
        return
    with _schema_lock:
        if _schema_initialized:
            return
        _ensure_postgres_schema_once()
        _schema_initialized = True


def _ensure_postgres_schema_once():
    with get_db_connection() as conn:
        cur = conn.cursor()
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS Brands (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(120) NOT NULL UNIQUE,
                slug VARCHAR(120) NULL,
                css_class VARCHAR(120) NULL,
                brand_font_key VARCHAR(40) NOT NULL DEFAULT 'inter'
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS Products (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                brand_id INTEGER NOT NULL REFERENCES Brands(id) ON DELETE RESTRICT,
                category VARCHAR(30) NOT NULL,
                item_category VARCHAR(60) NULL,
                serial VARCHAR(50) NOT NULL UNIQUE,
                name VARCHAR(180) NOT NULL,
                price INTEGER NOT NULL,
                max_days INTEGER NOT NULL,
                condition_score INTEGER NOT NULL,
                material VARCHAR(180) NULL,
                origin VARCHAR(180) NULL,
                condition VARCHAR(180) NULL,
                main_image VARCHAR(1000) NOT NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS ProductImages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id INTEGER NOT NULL REFERENCES Products(id) ON DELETE CASCADE,
                image_url VARCHAR(1000) NOT NULL,
                sort_order INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS ProductSizes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id INTEGER NOT NULL REFERENCES Products(id) ON DELETE CASCADE,
                size_label VARCHAR(40) NOT NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS ProductMeasurements (
                product_id INTEGER NOT NULL PRIMARY KEY REFERENCES Products(id) ON DELETE CASCADE,
                payload_json TEXT NOT NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS CampaignSettings (
                id INTEGER PRIMARY KEY,
                intro_en TEXT NULL,
                intro_ru TEXT NULL,
                tagline_en TEXT NULL,
                tagline_ru TEXT NULL
            )
            """
        )
        cur.execute("ALTER TABLE CampaignSettings ADD COLUMN IF NOT EXISTS members_area_hero_url TEXT NULL")
        cur.execute("INSERT INTO CampaignSettings (id) VALUES (1) ON CONFLICT (id) DO NOTHING")
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS CampaignLooks (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sort_order INTEGER NOT NULL DEFAULT 0,
                image_url VARCHAR(1000) NOT NULL,
                ref_text VARCHAR(180) NULL,
                location_text VARCHAR(180) NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS CampaignStories (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sort_order INTEGER NOT NULL DEFAULT 0,
                headline_en VARCHAR(240) NULL,
                headline_ru VARCHAR(240) NULL,
                body_en TEXT NULL,
                body_ru TEXT NULL,
                credits_en VARCHAR(500) NULL,
                credits_ru VARCHAR(500) NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS CampaignStoryImages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                story_id INTEGER NOT NULL REFERENCES CampaignStories(id) ON DELETE CASCADE,
                sort_order INTEGER NOT NULL DEFAULT 0,
                image_url VARCHAR(1000) NOT NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS AppUsers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL UNIQUE,
                password_hash VARCHAR(500) NOT NULL,
                display_name VARCHAR(120) NOT NULL,
                is_admin INTEGER NOT NULL DEFAULT 0,
                is_email_verified INTEGER NOT NULL DEFAULT 0,
                email_verification_code_hash VARCHAR(500) NULL,
                email_verification_expires_at TIMESTAMP NULL,
                email_verification_attempts INTEGER NOT NULL DEFAULT 0,
                level_code VARCHAR(30) NOT NULL DEFAULT 'bronze',
                lifetime_orders_count INTEGER NOT NULL DEFAULT 0,
                lifetime_spend_amount INTEGER NOT NULL DEFAULT 0,
                session_key_hash VARCHAR(128) NULL,
                session_expires_at TIMESTAMP NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS RentalOrders (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES AppUsers(id) ON DELETE CASCADE,
                status VARCHAR(30) NOT NULL DEFAULT 'created',
                pickup_code VARCHAR(40) NULL,
                total_items INTEGER NOT NULL,
                total_price INTEGER NOT NULL,
                rental_start_date DATE NULL,
                rental_end_date DATE NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS RentalOrderItems (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INTEGER NOT NULL REFERENCES RentalOrders(id) ON DELETE CASCADE,
                product_id INTEGER NULL,
                serial VARCHAR(50) NOT NULL,
                brand_name VARCHAR(120) NOT NULL,
                product_name VARCHAR(180) NOT NULL,
                size_label VARCHAR(40) NULL,
                rental_days INTEGER NOT NULL,
                price_per_day INTEGER NOT NULL,
                line_total INTEGER NOT NULL,
                image_url VARCHAR(1000) NULL,
                rental_start_date DATE NULL,
                rental_end_date DATE NULL
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS RentalOrderReviews (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id INTEGER NOT NULL REFERENCES RentalOrders(id) ON DELETE CASCADE,
                user_id INTEGER NOT NULL REFERENCES AppUsers(id),
                rating INTEGER NOT NULL,
                body VARCHAR(1000) NULL,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NULL,
                CONSTRAINT uq_rental_order_reviews_order_user UNIQUE (order_id, user_id)
            )
            """
        )
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS is_email_verified INTEGER NOT NULL DEFAULT 0")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS email_verification_code_hash VARCHAR(500) NULL")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS email_verification_expires_at TIMESTAMP NULL")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS email_verification_attempts INTEGER NOT NULL DEFAULT 0")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS level_code VARCHAR(30) NOT NULL DEFAULT 'bronze'")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS lifetime_orders_count INTEGER NOT NULL DEFAULT 0")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS lifetime_spend_amount INTEGER NOT NULL DEFAULT 0")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS session_key_hash VARCHAR(128) NULL")
        cur.execute("ALTER TABLE AppUsers ADD COLUMN IF NOT EXISTS session_expires_at TIMESTAMP NULL")
        cur.execute("ALTER TABLE RentalOrders ADD COLUMN IF NOT EXISTS pickup_code VARCHAR(40) NULL")
        cur.execute("ALTER TABLE RentalOrders ADD COLUMN IF NOT EXISTS rental_start_date DATE NULL")
        cur.execute("ALTER TABLE RentalOrders ADD COLUMN IF NOT EXISTS rental_end_date DATE NULL")
        cur.execute("ALTER TABLE RentalOrderItems ADD COLUMN IF NOT EXISTS rental_start_date DATE NULL")
        cur.execute("ALTER TABLE RentalOrderItems ADD COLUMN IF NOT EXISTS rental_end_date DATE NULL")
        cur.execute("ALTER TABLE Brands ADD COLUMN IF NOT EXISTS brand_font_key VARCHAR(40) NOT NULL DEFAULT 'inter'")
        cur.execute(
            """
            UPDATE Brands
            SET brand_font_key = CASE
                WHEN LOWER(TRIM(name)) = 'maison margiela' THEN 'inter'
                WHEN LOWER(TRIM(name)) = 'balenciaga' THEN 'inter'
                WHEN LOWER(TRIM(name)) = 'balenciaga couture' THEN 'cormorant-garamond'
                WHEN LOWER(TRIM(name)) = 'rick owens' THEN 'cormorant-garamond'
                WHEN LOWER(TRIM(name)) = 'yzy' THEN 'space-grotesk'
                WHEN LOWER(TRIM(name)) = 'raf simons' THEN 'inter'
                WHEN LOWER(TRIM(name)) = 'yohji yamamoto' THEN 'instrument-serif'
                WHEN LOWER(TRIM(name)) = 'vetements' THEN 'inter'
                WHEN LOWER(TRIM(name)) = 'comme des garçons' THEN 'bodoni-moda'
                WHEN LOWER(TRIM(name)) = 'schiaparelli' THEN 'bodoni-moda'
                ELSE brand_font_key
            END
            WHERE brand_font_key IS NULL
               OR TRIM(brand_font_key) = ''
               OR LOWER(TRIM(brand_font_key)) = 'inter'
            """
        )
        cur.execute("ALTER TABLE Products ADD COLUMN IF NOT EXISTS measurements_json TEXT NULL")
        cur.execute(
            """
            UPDATE CampaignSettings
            SET members_area_hero_url = NULL
            WHERE id = 1
              AND members_area_hero_url IS NOT NULL
              AND TRIM(members_area_hero_url) LIKE '/static%%'
            """
        )
        try:
            from seed_defaults import DEFAULT_CAMPAIGN_SETTINGS

            _hero = (DEFAULT_CAMPAIGN_SETTINGS.get('members_area_hero_url') or '').strip()
            if _hero:
                cur.execute(
                    """
                    UPDATE CampaignSettings
                    SET members_area_hero_url = ?
                    WHERE id = 1
                      AND (
                          members_area_hero_url IS NULL
                          OR TRIM(COALESCE(members_area_hero_url, '')) = ''
                      )
                    """,
                    (_hero,),
                )
        except Exception as exc:
            _logger.debug('members_area_hero_url default skipped: %s', exc)
        try:
            migrate_legacy_measurements_to_table(cur)
            sync_missing_product_measurements(cur)
        except Exception as exc:
            _logger.warning('Could not sync ProductMeasurements: %s', exc)
        conn.commit()
